### ISSUE TITLE
Unable to load DLL libRF62X-SDK.dll

### ISSUE THREAD

**Issue by alimoosavi1986** [RIFTEK-LLC/RF62X-SDK#2]
Thank you very much for solving the previous problem.
I found another problem, could you please help in this case as well
![Error](https://user-images.githubusercontent.com/10366499/149402587-7cb65bf3-534d-4287-a263-fe3cf2228694.jpg)

**Comment by KuzVlad** [comment]
Try the following steps:
*  Select **x64** or **x86** and **Debug** or **Release** target platform
*  Download `RF62X-SDK` dll-s from archive for WRAPPER .NET LANGUAGE (see [RF62X-SDK releases](https://github.com/RIFTEK-LLC/RF62X-SDK/releases) link).
*  Compile project
*  Copy the **libRF62X-SDK.dll** from the *Dependencies* folder of the downloaded archive into the path of the project executable (`../bin/x64/Debug/` or `../bin/x64/Release/`)
*  Run project

> For more information, you can read the [readme](https://github.com/RIFTEK-LLC/RF62X-SDK#creating-a-c-project) of the project, or you can also watch [demo-videos](https://cloud.riftek.com/index.php/s/PMDBEcB3BWK4xSZ) for your conditions.
