### ISSUE TITLE
How to set resolution?

### ISSUE THREAD

**Issue by T0maas** [RIFTEK-LLC/RF62X-SDK#3]
I am upgrading from older rf625 sdk. There was option to change resolution using `params.resolution = Res_1280`.
How to set same option using this sdk using c++ wrapper?

**Comment by KuzVlad** [comment]
`user_streams_pointsCount` - the number of points in the profile that the device calculates and sends.
```cpp
// 648 and 1296 points are available for setting
scanner->set_param("user_streams_pointsCount", 1296);
```
![image](https://user-images.githubusercontent.com/40023063/174478055-76485744-5dd7-4092-98fb-ed329b14a6fb.png)![image](https://user-images.githubusercontent.com/40023063/174478211-4b1744fd-b2af-4c61-b928-6d60bfce8b0a.png)
